"""adapter / Generator 单元测试。"""

import json
import shutil
import tempfile
import textwrap
import unittest
from pathlib import Path

from . import _setup  # noqa: F401

from lib.adapter import (  # noqa: E402
    ClaudeAdapter,
    ComateAdapter,
    DuccAdapter,
    GenerateContext,
    Generator,
)


RULES_YAML = textwrap.dedent("""\
architecture:
  layers:
    - name: component
      paths: ["src/components/", "src/pages/"]
      can_import: ["hook", "service", "type"]
    - name: hook
      paths: ["src/hooks/"]
      can_import: ["service", "type"]
    - name: service
      paths: ["src/api/"]
      can_import: ["type"]
imports:
  allowed_prefixes: ["@/types", "@/api", "@/components"]
  forbidden_imports: ["@/services", "@/api/mockApi"]
naming:
  component: PascalCase
  hook: camelCase-with-use-prefix
""")


PROJECT_CONTEXT = {
    "summary": {
        "total_files": 10,
        "total_components": 4,
        "total_hooks": 2,
        "total_apis": 3,
        "total_types": 1,
    },
    "components": [
        {"name": "Btn", "file_path": "src/components/Btn.tsx"},
        {"name": "Header", "file_path": "src/components/Header.tsx"},
    ],
    "hooks": [{"name": "useFoo", "file_path": "src/hooks/useFoo.ts"}],
    "apis": [{"name": "itemService", "file_path": "src/api/itemService.ts"}],
    "types": [{"name": "Item", "file_path": "src/types/item.ts"}],
}


def _make_ctx(rules=None, project_context=None, lessons=None):
    return GenerateContext(
        rules=rules if rules is not None else {},
        project_context=project_context if project_context is not None else {},
        lessons=lessons or [],
        version="2.0.0-test",
        timestamp="2026-06-17T20:00:00",
    )


# ---------------------------------------------------------------------------
# 单 adapter 渲染
# ---------------------------------------------------------------------------


class TestAdapterRender(unittest.TestCase):
    def setUp(self):
        import yaml
        self.rules = yaml.safe_load(RULES_YAML)
        self.ctx = _make_ctx(
            rules=self.rules,
            project_context=PROJECT_CONTEXT,
            lessons=[
                {
                    "id": "L1", "title": "禁止 @/services",
                    "category": "import", "severity": "error",
                    "keywords": ["forbidden"], "applies_to": ["src/api/"],
                    "content": "已迁移到 @/api。", "author": "alice",
                    "created_at": "2026-06-01T10:00:00", "expires_at": None,
                }
            ],
        )

    def test_header_contains_version_and_timestamp(self):
        out = ClaudeAdapter().render(self.ctx)
        self.assertIn("generated by harness 2.0.0-test", out)
        self.assertIn("2026-06-17T20:00:00", out)
        self.assertTrue(out.startswith("<!--"))

    def test_claude_renders_architecture_table_and_imports(self):
        out = ClaudeAdapter().render(self.ctx)
        # 表格表头
        self.assertIn("| 层级 | 路径 | 可导入 |", out)
        # layers 内容
        self.assertIn("component", out)
        self.assertIn("src/components/", out)
        # 禁止导入
        self.assertIn("@/services", out)
        self.assertIn("@/api/mockApi", out)
        # 项目状态
        self.assertIn("文件数: 10", out)
        self.assertIn("组件:   4", out)
        # 经验注入
        self.assertIn("禁止 @/services", out)
        self.assertIn("已迁移到 @/api", out)

    def test_comate_inlines_everything_no_at_refs(self):
        out = ComateAdapter().render(self.ctx)
        # 不能出现 Claude 的 @ 引用风格
        self.assertNotIn("@/.harness/rules.yaml", out)
        self.assertNotIn("@.harness/generated/", out)
        # 但仍带规则正文
        self.assertIn("禁止导入", out)
        self.assertIn("@/services", out)
        # 类型/API 列表
        self.assertIn("Item", out)
        self.assertIn("itemService", out)

    def test_ducc_uses_bullets_for_layers(self):
        out = DuccAdapter().render(self.ctx)
        # bullet 风格
        self.assertIn("- **component**", out)
        self.assertIn("- **hook**", out)
        # 同样有经验
        self.assertIn("禁止 @/services", out)

    def test_target_path(self):
        from pathlib import Path as P
        harness = P("/tmp/x/.harness")
        self.assertEqual(
            ClaudeAdapter().target_path(harness),
            harness / "generated" / "claude.md",
        )
        self.assertEqual(
            ComateAdapter().target_path(harness),
            harness / "generated" / "comate.md",
        )
        self.assertEqual(
            DuccAdapter().target_path(harness),
            harness / "generated" / "ducc.md",
        )


# ---------------------------------------------------------------------------
# 边界：缺数据时的降级
# ---------------------------------------------------------------------------


class TestAdapterEdgeCases(unittest.TestCase):
    def test_no_rules_no_scan_no_lessons(self):
        ctx = _make_ctx()
        for adapter in (ClaudeAdapter(), ComateAdapter(), DuccAdapter()):
            out = adapter.render(ctx)
            self.assertIn("rules.yaml 未配置 architecture.layers", out)
            self.assertIn("尚未运行 scan", out)
            self.assertIn("暂无经验记录", out)

    def test_long_lesson_is_truncated(self):
        long_body = "x" * 600
        ctx = _make_ctx(
            lessons=[{
                "id": "L", "title": "超长", "category": "general",
                "severity": "warning", "keywords": [], "applies_to": [],
                "content": long_body, "author": "a",
                "created_at": "2026-06-01T00:00:00", "expires_at": None,
            }],
        )
        out = ClaudeAdapter().render(ctx)
        # 截断到 300 字符 + 省略号
        self.assertIn("…", out)
        self.assertNotIn("x" * 400, out)


# ---------------------------------------------------------------------------
# Generator 集成
# ---------------------------------------------------------------------------


class GeneratorFixture:
    def __init__(self):
        self.root = Path(tempfile.mkdtemp(prefix="harness-gen-")).resolve()
        self.harness_dir = self.root / ".harness"
        self.harness_dir.mkdir()

    def write_rules(self, content: str = RULES_YAML):
        (self.harness_dir / "rules.yaml").write_text(content, encoding="utf-8")

    def write_project_context(self, data=PROJECT_CONTEXT):
        ctx_dir = self.harness_dir / "context"
        ctx_dir.mkdir(parents=True, exist_ok=True)
        (ctx_dir / "project-context.json").write_text(
            json.dumps(data, ensure_ascii=False), encoding="utf-8")

    def write_lesson(self, lesson_id: str, **frontmatter):
        from lib.experience_market import ExperienceMarket
        m = ExperienceMarket(harness_dir=self.harness_dir)
        m.add_lesson(
            title=frontmatter.get("title", "t"),
            content=frontmatter.get("content", "body"),
            category=frontmatter.get("category", "general"),
            severity=frontmatter.get("severity", "warning"),
            keywords=frontmatter.get("keywords", []),
            applies_to=frontmatter.get("applies_to", []),
            lesson_id=lesson_id,
            expires_at=frontmatter.get("expires_at"),
        )

    def gen(self) -> Generator:
        return Generator(harness_dir=self.harness_dir, version="2.0.0-test")

    def cleanup(self):
        shutil.rmtree(self.root, ignore_errors=True)


class TestGenerator(unittest.TestCase):
    def setUp(self):
        self.fx = GeneratorFixture()

    def tearDown(self):
        self.fx.cleanup()

    def test_generate_writes_three_files(self):
        self.fx.write_rules()
        self.fx.write_project_context()
        result = self.fx.gen().generate_all()

        self.assertEqual(len(result.written), 3)
        out_dir = self.fx.harness_dir / "generated"
        self.assertTrue((out_dir / "claude.md").exists())
        self.assertTrue((out_dir / "comate.md").exists())
        self.assertTrue((out_dir / "ducc.md").exists())

        # claude.md 包含从 rules.yaml 来的实际内容
        text = (out_dir / "claude.md").read_text(encoding="utf-8")
        self.assertIn("@/services", text)
        self.assertIn("文件数: 10", text)

    def test_generate_loads_lessons_and_skips_expired(self):
        self.fx.write_rules()
        self.fx.write_project_context()
        self.fx.write_lesson("active", title="有效",
                             content="active body",
                             keywords=["k"])
        self.fx.write_lesson("expired", title="过期",
                             content="expired body",
                             expires_at="2020-01-01T00:00:00")
        self.fx.gen().generate_all()

        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("有效", text)
        self.assertIn("active body", text)
        self.assertNotIn("过期", text)
        self.assertNotIn("expired body", text)

    def test_generate_works_without_scan(self):
        # 没有 project-context.json 也不应崩
        self.fx.write_rules()
        result = self.fx.gen().generate_all()
        self.assertEqual(len(result.written), 3)
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("尚未运行 scan", text)
        # 但架构规则仍然完整
        self.assertIn("component", text)

    def test_generate_works_without_rules(self):
        # 连 rules.yaml 都没有也不应崩（只是内容降级）
        result = self.fx.gen().generate_all()
        self.assertEqual(len(result.written), 3)
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("rules.yaml 未配置 architecture.layers", text)

    def test_overwrites_existing(self):
        self.fx.write_rules()
        out_dir = self.fx.harness_dir / "generated"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "claude.md").write_text("STALE", encoding="utf-8")

        self.fx.gen().generate_all()
        text = (out_dir / "claude.md").read_text(encoding="utf-8")
        self.assertNotIn("STALE", text)
        self.assertIn("项目规范", text)

    def test_relative_path_in_result(self):
        self.fx.write_rules()
        result = self.fx.gen().generate_all()
        # 路径相对 project_dir，便于 CLI 打印
        for p in result.written:
            self.assertTrue(p.startswith(".harness/generated/"))


if __name__ == "__main__":
    unittest.main()
