"""adapter / Generator 单元测试。"""

import json
import shutil
import tempfile
import textwrap
import unittest
from pathlib import Path

from . import _setup  # noqa: F401

from lib.adapter import (  # noqa: E402
    ClaudeAdapter,
    ComateAdapter,
    DuccAdapter,
    GenerateContext,
    Generator,
    ReadmeAdapter,
    README_AUTO_BEGIN,
    README_AUTO_END,
    README_HANDWRITTEN_BEGIN,
    README_HANDWRITTEN_END,
)


RULES_YAML = textwrap.dedent("""\
architecture:
  sub_layer_convention:
    components: component
    hooks: hook
    utils: util
  layers:
    - name: component
      paths: ["src/components/", "src/pages/"]
      can_import: ["hook", "service", "type"]
    - name: hook
      paths: ["src/hooks/"]
      can_import: ["service", "type"]
    - name: service
      paths: ["src/api/"]
      can_import: ["type"]
imports:
  allowed_prefixes: ["@/types", "@/api", "@/components"]
  forbidden_imports: ["@/services", "@/api/mockApi"]
naming:
  component: PascalCase
  hook: camelCase-with-use-prefix
""")


PROJECT_CONTEXT = {
    "summary": {
        "total_files": 10,
        "total_components": 4,
        "total_hooks": 2,
        "total_apis": 3,
        "total_types": 1,
    },
    "components": [
        {"name": "Btn", "file_path": "src/components/Btn.tsx"},
        {"name": "Header", "file_path": "src/components/Header.tsx"},
    ],
    "hooks": [{"name": "useFoo", "file_path": "src/hooks/useFoo.ts"}],
    "apis": [{"name": "itemService", "file_path": "src/api/itemService.ts"}],
    "types": [{"name": "Item", "file_path": "src/types/item.ts"}],
}


def _make_ctx(rules=None, project_context=None, lessons=None):
    return GenerateContext(
        rules=rules if rules is not None else {},
        project_context=project_context if project_context is not None else {},
        lessons=lessons or [],
        version="2.0.0-test",
        timestamp="2026-06-17T20:00:00",
    )


# ---------------------------------------------------------------------------
# 单 adapter 渲染
# ---------------------------------------------------------------------------


class TestAdapterRender(unittest.TestCase):
    def setUp(self):
        import yaml
        self.rules = yaml.safe_load(RULES_YAML)
        self.ctx = _make_ctx(
            rules=self.rules,
            project_context=PROJECT_CONTEXT,
            lessons=[
                {
                    "id": "L1", "title": "禁止 @/services",
                    "category": "import", "severity": "error",
                    "keywords": ["forbidden"], "applies_to": ["src/api/"],
                    "content": "已迁移到 @/api。", "author": "alice",
                    "created_at": "2026-06-01T10:00:00", "expires_at": None,
                }
            ],
        )

    def test_header_contains_version_and_timestamp(self):
        out = ClaudeAdapter().render(self.ctx)
        self.assertIn("generated by harness 2.0.0-test", out)
        self.assertIn("2026-06-17T20:00:00", out)
        self.assertTrue(out.startswith("<!--"))

    def test_claude_renders_architecture_table_and_imports(self):
        out = ClaudeAdapter().render(self.ctx)
        # 表格表头
        self.assertIn("| 层级 | 路径 | 可导入 |", out)
        # layers 内容
        self.assertIn("component", out)
        self.assertIn("src/components/", out)
        # 禁止导入
        self.assertIn("@/services", out)
        self.assertIn("@/api/mockApi", out)
        # 项目状态
        self.assertIn("文件数: 10", out)
        self.assertIn("组件:   4", out)
        # 经验注入
        self.assertIn("禁止 @/services", out)
        self.assertIn("已迁移到 @/api", out)

    def test_comate_inlines_everything_no_at_refs(self):
        out = ComateAdapter().render(self.ctx)
        # 不能出现 Claude 的 @ 引用风格
        self.assertNotIn("@/.harness/rules.yaml", out)
        self.assertNotIn("@.harness/generated/", out)
        # 但仍带规则正文
        self.assertIn("禁止导入", out)
        self.assertIn("@/services", out)
        # 类型/API 列表
        self.assertIn("Item", out)
        self.assertIn("itemService", out)

    def test_ducc_uses_bullets_for_layers(self):
        out = DuccAdapter().render(self.ctx)
        # bullet 风格
        self.assertIn("- **component**", out)
        self.assertIn("- **hook**", out)
        # 同样有经验
        self.assertIn("禁止 @/services", out)

    def test_target_path(self):
        from pathlib import Path as P
        harness = P("/tmp/x/.harness")
        self.assertEqual(
            ClaudeAdapter().target_path(harness),
            harness / "generated" / "claude.md",
        )
        self.assertEqual(
            ComateAdapter().target_path(harness),
            harness / "generated" / "comate.md",
        )
        self.assertEqual(
            DuccAdapter().target_path(harness),
            harness / "generated" / "ducc.md",
        )

    def test_claude_renders_harness_new_help(self):
        """B3: generated/claude.md 必须包含 harness new --path 用法说明。"""
        out = ClaudeAdapter().render(self.ctx)
        # 标题节
        self.assertIn("## 🆕 新建文件", out)
        # 命令签名
        self.assertIn("harness new <kind> <name>", out)
        # --path / --force 都要写出来
        self.assertIn("--path", out)
        self.assertIn("--force", out)
        # 至少一个 --path 例子
        self.assertIn("--path src/widgets/", out)
        # 优先级说明
        self.assertIn("优先级", out)

    def test_ducc_renders_harness_new_help(self):
        """Ducc adapter 同样要带 harness new 用法。"""
        out = DuccAdapter().render(self.ctx)
        self.assertIn("## 🆕 新建文件", out)
        self.assertIn("--path", out)

    def test_new_help_uses_rules_default_dir(self):
        """例子里的 default_dir 应跟 rules.yaml 当前值（不写死 src/components/）。"""
        # 改 rules：把 component 默认目录设成 src/widgets/
        rules = dict(self.rules)
        rules["templates"] = {
            "kinds": {
                "component": {
                    "default_dir": "src/widgets/",
                    "extension": ".tsx",
                },
            },
        }
        ctx = _make_ctx(rules=rules, project_context=PROJECT_CONTEXT, lessons=[])
        out = ClaudeAdapter().render(ctx)
        # 例子中的默认路径应反映 rules.yaml 改动
        self.assertIn("src/widgets/UserAvatar.tsx", out)

    def test_adapters_render_sub_layer_convention(self):
        """Agent 文档必须展示局部子目录归层，避免误判 paths 前缀。"""
        for adapter in (ClaudeAdapter(), ComateAdapter(), DuccAdapter()):
            out = adapter.render(self.ctx)
            self.assertIn("局部子目录归层", out)
            self.assertIn("优先级高于 paths 前缀匹配", out)
            self.assertIn("| `components` | component |", out)
            self.assertIn("| `hooks` | hook |", out)
            self.assertIn("| `utils` | util |", out)

    def test_claude_warns_not_to_downgrade_mode_to_bypass_validation(self):
        out = ClaudeAdapter().render(self.ctx)
        self.assertIn("不要为了绕过验证自行执行 `harness mode relaxed/off`", out)


# ---------------------------------------------------------------------------
# 边界：缺数据时的降级
# ---------------------------------------------------------------------------


class TestAdapterEdgeCases(unittest.TestCase):
    def test_no_rules_no_scan_no_lessons(self):
        ctx = _make_ctx()
        for adapter in (ClaudeAdapter(), ComateAdapter(), DuccAdapter()):
            out = adapter.render(ctx)
            self.assertIn("rules.yaml 未配置 architecture.layers", out)
            self.assertIn("尚未运行 scan", out)
            self.assertIn("暂无经验记录", out)

    def test_long_lesson_is_truncated(self):
        long_body = "x" * 600
        ctx = _make_ctx(
            lessons=[{
                "id": "L", "title": "超长", "category": "general",
                "severity": "warning", "keywords": [], "applies_to": [],
                "content": long_body, "author": "a",
                "created_at": "2026-06-01T00:00:00", "expires_at": None,
            }],
        )
        out = ClaudeAdapter().render(ctx)
        # 截断到 300 字符 + 省略号
        self.assertIn("…", out)
        self.assertNotIn("x" * 400, out)


# ---------------------------------------------------------------------------
# Generator 集成
# ---------------------------------------------------------------------------


class GeneratorFixture:
    def __init__(self):
        self.root = Path(tempfile.mkdtemp(prefix="harness-gen-")).resolve()
        self.harness_dir = self.root / ".harness"
        self.harness_dir.mkdir()

    def write_rules(self, content: str = RULES_YAML):
        (self.harness_dir / "rules.yaml").write_text(content, encoding="utf-8")

    def write_project_context(self, data=PROJECT_CONTEXT):
        ctx_dir = self.harness_dir / "context"
        ctx_dir.mkdir(parents=True, exist_ok=True)
        (ctx_dir / "project-context.json").write_text(
            json.dumps(data, ensure_ascii=False), encoding="utf-8")

    def write_lesson(self, lesson_id: str, **frontmatter):
        from lib.experience_market import ExperienceMarket
        m = ExperienceMarket(harness_dir=self.harness_dir)
        m.add_lesson(
            title=frontmatter.get("title", "t"),
            content=frontmatter.get("content", "body"),
            category=frontmatter.get("category", "general"),
            severity=frontmatter.get("severity", "warning"),
            keywords=frontmatter.get("keywords", []),
            applies_to=frontmatter.get("applies_to", []),
            lesson_id=lesson_id,
            expires_at=frontmatter.get("expires_at"),
        )

    def gen(self) -> Generator:
        return Generator(harness_dir=self.harness_dir, version="2.0.0-test")

    def cleanup(self):
        shutil.rmtree(self.root, ignore_errors=True)


class TestGenerator(unittest.TestCase):
    def setUp(self):
        self.fx = GeneratorFixture()

    def tearDown(self):
        self.fx.cleanup()

    def test_generate_writes_three_files(self):
        self.fx.write_rules()
        self.fx.write_project_context()
        result = self.fx.gen().generate_all()

        # 默认 5 个 adapter：claude / comate / ducc / readme / hooks-config
        self.assertEqual(len(result.written), 5)
        out_dir = self.fx.harness_dir / "generated"
        self.assertTrue((out_dir / "claude.md").exists())
        self.assertTrue((out_dir / "comate.md").exists())
        self.assertTrue((out_dir / "ducc.md").exists())
        # README 不在 generated/ 而是直接进 .harness/
        self.assertTrue((self.fx.harness_dir / "README.md").exists())
        # hooks/.config.sh 直接进 .harness/hooks/
        self.assertTrue((self.fx.harness_dir / "hooks" / ".config.sh").exists())

        # claude.md 包含从 rules.yaml 来的实际内容
        text = (out_dir / "claude.md").read_text(encoding="utf-8")
        self.assertIn("@/services", text)
        self.assertIn("文件数: 10", text)

    def test_generate_loads_lessons_and_skips_expired(self):
        self.fx.write_rules()
        self.fx.write_project_context()
        self.fx.write_lesson("active", title="有效",
                             content="active body",
                             keywords=["k"])
        self.fx.write_lesson("expired", title="过期",
                             content="expired body",
                             expires_at="2020-01-01T00:00:00")
        self.fx.gen().generate_all()

        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("有效", text)
        self.assertIn("active body", text)
        self.assertNotIn("过期", text)
        self.assertNotIn("expired body", text)

    def test_generate_works_without_scan(self):
        # 没有 project-context.json 也不应崩
        self.fx.write_rules()
        result = self.fx.gen().generate_all()
        self.assertEqual(len(result.written), 5)
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("尚未运行 scan", text)
        # 但架构规则仍然完整
        self.assertIn("component", text)

    def test_generate_works_without_rules(self):
        # 连 rules.yaml 都没有也不应崩（只是内容降级）
        result = self.fx.gen().generate_all()
        self.assertEqual(len(result.written), 5)
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertIn("rules.yaml 未配置 architecture.layers", text)

    def test_overwrites_existing(self):
        self.fx.write_rules()
        out_dir = self.fx.harness_dir / "generated"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "claude.md").write_text("STALE", encoding="utf-8")

        self.fx.gen().generate_all()
        text = (out_dir / "claude.md").read_text(encoding="utf-8")
        self.assertNotIn("STALE", text)
        self.assertIn("项目规范", text)

    def test_relative_path_in_result(self):
        self.fx.write_rules()
        result = self.fx.gen().generate_all()
        # 路径相对 project_dir，便于 CLI 打印
        for p in result.written:
            self.assertTrue(
                p.startswith(".harness/"),
                f"unexpected path {p!r}",
            )

    def test_hooks_config_written_with_scanner_values(self):
        """A3: .harness/hooks/.config.sh 由 rules.yaml scanner.* 推导出来。"""
        self.fx.write_rules()
        self.fx.gen().generate_all()
        cfg = self.fx.harness_dir / "hooks" / ".config.sh"
        self.assertTrue(cfg.exists())
        text = cfg.read_text(encoding="utf-8")
        # 头部 marker(human 看得到 + grep 友好)
        self.assertIn("Auto-generated by harness", text)
        self.assertIn("DO NOT EDIT", text)
        # rules.yaml 里的 scanner.source_root / include_extensions 应当出现
        self.assertIn("HARNESS_SOURCE_ROOT='src'", text)
        self.assertIn("'.ts'", text)
        self.assertIn("'.tsx'", text)
        # 默认 strict
        self.assertIn("HARNESS_MODE='strict'", text)
        # experience_market.enabled=true → 1
        self.assertIn("HARNESS_EXPERIENCE_ENABLED=1", text)

    def test_hooks_config_falls_back_when_rules_missing(self):
        """rules.yaml 缺失也要写出可用的 .config.sh(默认值兜底)。"""
        self.fx.gen().generate_all()
        cfg = self.fx.harness_dir / "hooks" / ".config.sh"
        self.assertTrue(cfg.exists())
        text = cfg.read_text(encoding="utf-8")
        self.assertIn("HARNESS_SOURCE_ROOT='src'", text)
        self.assertIn("'.ts'", text)


# ---------------------------------------------------------------------------
# README adapter：自动区 + 手写区 + 源文件指纹
# ---------------------------------------------------------------------------


class TestReadmeAdapter(unittest.TestCase):
    def setUp(self):
        self.fx = GeneratorFixture()
        self.fx.write_rules()
        self.fx.write_project_context()

    def tearDown(self):
        self.fx.cleanup()

    def _readme(self) -> Path:
        return self.fx.harness_dir / "README.md"

    def test_first_run_writes_default_handwritten_block(self):
        self.fx.gen().generate_all()
        text = self._readme().read_text(encoding="utf-8")

        # 顶部 marker
        self.assertIn("AUTOGENERATED by harness 2.0.0-test", text)
        self.assertIn("<!-- sources:", text)
        # 自动区/手写区两块都在
        self.assertIn(README_AUTO_BEGIN, text)
        self.assertIn(README_AUTO_END, text)
        self.assertIn(README_HANDWRITTEN_BEGIN, text)
        self.assertIn(README_HANDWRITTEN_END, text)
        # 自动区有规则内容
        self.assertIn("@/services", text)
        self.assertIn("strict", text)  # mode
        # 手写区有默认模板示例
        self.assertIn("背景与原则", text)

    def test_second_run_preserves_handwritten_edits(self):
        self.fx.gen().generate_all()
        original = self._readme().read_text(encoding="utf-8")

        # 模拟用户手改了手写区
        edited = original.replace(
            "## 背景与原则（手写区）",
            "## 背景与原则（手写区）\n\n这是我自己写的内容 ABCD123",
        )
        self._readme().write_text(edited, encoding="utf-8")

        # 再生成一次：手写区必须保留，自动区刷新
        self.fx.gen().generate_all()
        after = self._readme().read_text(encoding="utf-8")
        self.assertIn("ABCD123", after, "手写区被覆盖了")
        # 自动区仍然在（且包含规则）
        self.assertIn("@/services", after)

    def test_second_run_overwrites_autogenerated_block(self):
        self.fx.gen().generate_all()
        original = self._readme().read_text(encoding="utf-8")

        # 模拟有人手改了自动区里的内容（只动自动区，避免污染手写区）
        auto = ReadmeAdapter.extract_auto_block(original)
        self.assertIsNotNone(auto)
        tampered = original.replace(
            auto, auto.replace("@/services", "@/SOMETHING_BROKEN"))
        self._readme().write_text(tampered, encoding="utf-8")

        # 再生成：自动区会被覆盖回正
        self.fx.gen().generate_all()
        after_auto = ReadmeAdapter.extract_auto_block(
            self._readme().read_text(encoding="utf-8"))
        self.assertIn("@/services", after_auto)
        self.assertNotIn("@/SOMETHING_BROKEN", after_auto)

    def test_source_hashes_change_when_rules_change(self):
        self.fx.gen().generate_all()
        first = ReadmeAdapter.extract_source_hashes(
            self._readme().read_text(encoding="utf-8"))
        self.assertIn("rules.yaml", first)
        self.assertIn("lessons", first)
        self.assertIn("mode-config.json", first)

        # 改 rules.yaml，重生成；rules.yaml 的 sha 应当变
        (self.fx.harness_dir / "rules.yaml").write_text(
            RULES_YAML + "\n# tweak\n", encoding="utf-8")
        self.fx.gen().generate_all()
        second = ReadmeAdapter.extract_source_hashes(
            self._readme().read_text(encoding="utf-8"))
        self.assertNotEqual(first["rules.yaml"], second["rules.yaml"])
        # lessons 没动，应该不变
        self.assertEqual(first["lessons"], second["lessons"])

    def test_extract_handwritten_returns_none_for_missing_markers(self):
        self.assertIsNone(ReadmeAdapter._extract_handwritten(""))
        self.assertIsNone(ReadmeAdapter._extract_handwritten("just text"))

    def test_onboarding_block_at_top(self):
        """B7: 接入说明应位于 README 头部、AUTOGENERATED 之前。"""
        self.fx.gen().generate_all()
        text = self._readme().read_text(encoding="utf-8")
        # 接入说明出现位置在 AUTOGENERATED START 之前
        idx_onboarding = text.find("在新项目中接入 harness")
        idx_auto_begin = text.find(README_AUTO_BEGIN)
        self.assertGreater(idx_onboarding, 0, "接入说明应该在文档里")
        self.assertGreater(idx_auto_begin, idx_onboarding,
                           "接入说明应在 AUTOGENERATED 之前")

    def test_onboarding_block_mentions_setup(self):
        """接入说明应推荐 harness setup 命令。"""
        self.fx.gen().generate_all()
        text = self._readme().read_text(encoding="utf-8")
        self.assertIn("harness setup", text)
        self.assertIn("--agent claude", text)

    def test_onboarding_block_has_old_project_section(self):
        """接入说明里要有"老项目接入"务实派子节,讲只管增量不管存量。"""
        self.fx.gen().generate_all()
        text = self._readme().read_text(encoding="utf-8")
        self.assertIn("老项目接入", text)
        # "只管增量"或"不管存量"是核心论断
        self.assertTrue(
            "只管增量" in text or "不管存量" in text,
            "老项目章节应表达 只管增量/不管存量 立场",
        )

    def test_extract_auto_block_returns_content(self):
        wrapped = f"head\n{README_AUTO_BEGIN}\n\nINSIDE\n\n{README_AUTO_END}\nfoot"
        got = ReadmeAdapter.extract_auto_block(wrapped)
        self.assertEqual(got, "INSIDE")

    def test_lessons_hash_changes_when_lesson_added(self):
        self.fx.gen().generate_all()
        first = ReadmeAdapter.extract_source_hashes(
            self._readme().read_text(encoding="utf-8"))
        self.fx.write_lesson("L1", title="t", content="body")
        self.fx.gen().generate_all()
        second = ReadmeAdapter.extract_source_hashes(
            self._readme().read_text(encoding="utf-8"))
        self.assertNotEqual(first["lessons"], second["lessons"])

    def test_experience_disabled_skips_lessons(self):
        """A1: rules.yaml experience_market.enabled=false → adapter 不渲染 lessons。"""
        # 写入一条 lesson + rules.yaml 关掉 experience
        self.fx.write_lesson("L1", title="不该出现", content="hidden body")
        rules_path = self.fx.harness_dir / "rules.yaml"
        rules_path.write_text(
            RULES_YAML + "\nexperience_market:\n  enabled: false\n",
            encoding="utf-8")
        self.fx.gen().generate_all()
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertNotIn("不该出现", text)
        self.assertNotIn("hidden body", text)
        # 索引段会落到"暂无经验记录"
        self.assertIn("暂无经验记录", text)

    def test_max_lessons_caps_lesson_count(self):
        """A1: experience_market.max_lessons=2 → adapter brief 渲染最多 2 条。"""
        for i in range(5):
            self.fx.write_lesson(
                f"L{i}", title=f"经验{i}", content=f"body {i}")
        rules_path = self.fx.harness_dir / "rules.yaml"
        rules_path.write_text(
            RULES_YAML + "\nexperience_market:\n  max_lessons: 2\n",
            encoding="utf-8")
        self.fx.gen().generate_all()
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        # 还有 3 条经验提示
        self.assertIn("还有 3 条经验", text)

    def test_project_constraints_render_at_top(self):
        """B8: rules.yaml project_constraints → claude.md 在 ⛔ 强制规则之前出现。"""
        rules_path = self.fx.harness_dir / "rules.yaml"
        rules_path.write_text(
            RULES_YAML
            + "\nproject_constraints:\n"
            + "  - title: 不允许 default export\n"
            + "    why: tree-shake 友好\n"
            + "    example: 'export const Foo'\n"
            + "  - 纯文本约束也行\n",
            encoding="utf-8")
        self.fx.gen().generate_all()
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        # 标题
        self.assertIn("🚨 项目硬约束", text)
        # 两条约束都在
        self.assertIn("不允许 default export", text)
        self.assertIn("纯文本约束也行", text)
        # 顺序:🚨 在 ⛔ 之前
        idx_constraint = text.find("🚨 项目硬约束")
        idx_rules = text.find("⛔ 强制规则")
        self.assertGreater(idx_rules, idx_constraint,
                           "硬约束章节必须在 ⛔ 强制规则之前")

    def test_project_constraints_section_omitted_when_empty(self):
        """没有 project_constraints → 整个章节不渲染(避免空标题)。"""
        self.fx.write_rules()
        self.fx.gen().generate_all()
        text = (self.fx.harness_dir / "generated" / "claude.md").read_text(
            encoding="utf-8")
        self.assertNotIn("🚨 项目硬约束", text)

    def test_mode_appears_in_readme(self):
        # 默认无 mode-config 时回落 strict
        self.fx.gen().generate_all()
        self.assertIn("`strict`",
                      self._readme().read_text(encoding="utf-8"))

        # 写入 relaxed 后重生成
        (self.fx.harness_dir / "mode-config.json").write_text(
            json.dumps({"mode": "relaxed", "updated_at": "2026-06-23T00:00:00"}),
            encoding="utf-8")
        self.fx.gen().generate_all()
        text = self._readme().read_text(encoding="utf-8")
        self.assertIn("**mode**: `relaxed`", text)


if __name__ == "__main__":
    unittest.main()
