# Auto-generated by harness 2.0.0-alpha.1 at 2026-06-26T14:19:40
# DO NOT EDIT — run `harness generate` to refresh.
# Sourced by .harness/hooks/*.sh for fast-path filtering before
# invoking the Python CLI. Stale values fall back to the CLI path.

HARNESS_SOURCE_ROOT='src'
HARNESS_INCLUDE_EXT=( '.ts' '.tsx' '.d.ts' )
HARNESS_EXCLUDE_DIRS=( 'node_modules' 'dist' 'build' '.git' '.harness' '.harness-shared' '_archived_harness_1.x' )
HARNESS_MODE='strict'
HARNESS_EXPERIENCE_ENABLED=1
