#!/usr/bin/env python3
"""Harness 2.0 Agent 适配器（P1 #9）—— lib/adapter.py

P1 范围（与执行清单一致）：
- 三个适配器：ClaudeAdapter / ComateAdapter / DuccAdapter
- 输出到 .harness/generated/{claude,comate,ducc}.md（不动项目根）
- 文件首行带时间戳 + 版本注释；用户改这些文件不会被尊重，下次 scan 会盖掉
- 内容来源：rules.yaml + context/project-context.json + memory/lessons/
- 经验注入：把 ExperienceMarket.list_lessons() 中未过期的 lesson 摘要整合进文档
  （静态注入：scan 时一次性渲染到 generated/*.md，由 CLAUDE.md 的 @-import 注入会话上下文）

设计原则：
- 每个 adapter 的 render() 是纯函数：输入 GenerateContext，输出 markdown 字符串
- Generator 只负责组装数据 + 调度落盘；adapter 不直接读盘
- scan 缺失（首次启动）时 generate 仍能跑，只是缺统计部分
"""

from __future__ import annotations

import datetime as _dt
import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# 数据载体
# ---------------------------------------------------------------------------


@dataclass
class GenerateContext:
    """生成所需的全部数据。"""

    rules: Dict[str, Any]
    project_context: Dict[str, Any]      # project-context.json；缺失时为 {}
    lessons: List[Dict[str, Any]]         # Lesson 序列化后的 dict，已过滤过期
    version: str
    timestamp: str                        # ISO 8601


# ---------------------------------------------------------------------------
# Adapter 基类
# ---------------------------------------------------------------------------


class AgentAdapter(ABC):
    """单个 Agent 的渲染规则。"""

    @property
    @abstractmethod
    def name(self) -> str:
        """文件名（不含扩展名），如 'claude'。"""

    @property
    def display_name(self) -> str:
        """人读名称，用于注释里显示。"""
        return self.name

    @abstractmethod
    def render_body(self, ctx: GenerateContext) -> str:
        """渲染除头部注释外的正文。"""

    # -- 通用入口 -----------------------------------------------------------

    def render(self, ctx: GenerateContext) -> str:
        header = (
            f"<!-- generated by harness {ctx.version} at {ctx.timestamp}"
            f" for {self.display_name}; do not edit, run `harness generate` to refresh -->\n\n"
        )
        return header + self.render_body(ctx).rstrip() + "\n"

    def target_path(self, harness_dir: Path) -> Path:
        return harness_dir / "generated" / f"{self.name}.md"


# ---------------------------------------------------------------------------
# 通用渲染片段（三个 adapter 共享）
# ---------------------------------------------------------------------------


def _render_architecture_table(rules: Dict[str, Any]) -> str:
    layers = (rules.get("architecture") or {}).get("layers") or []
    if not layers:
        return "（rules.yaml 未配置 architecture.layers）"
    lines = ["| 层级 | 路径 | 可导入 |", "|------|------|--------|"]
    for layer in layers:
        name = layer.get("name", "")
        paths = ", ".join(layer.get("paths") or []) or "-"
        can = ", ".join(layer.get("can_import") or []) or "（无）"
        lines.append(f"| {name} | {paths} | {can} |")
    return "\n".join(lines)


def _render_architecture_bullets(rules: Dict[str, Any]) -> str:
    layers = (rules.get("architecture") or {}).get("layers") or []
    if not layers:
        return "- （rules.yaml 未配置 architecture.layers）"
    lines = []
    for layer in layers:
        name = layer.get("name", "")
        paths = ", ".join(layer.get("paths") or []) or "-"
        can = ", ".join(layer.get("can_import") or []) or "无"
        lines.append(f"- **{name}** (`{paths}`) → 可导入: {can}")
    return "\n".join(lines)


def _render_imports(rules: Dict[str, Any]) -> str:
    imp = rules.get("imports") or {}
    allowed = imp.get("allowed_prefixes") or []
    forbidden = imp.get("forbidden_imports") or []
    parts = []
    if allowed:
        parts.append("**允许前缀**: " + ", ".join(f"`{p}`" for p in allowed))
    if forbidden:
        parts.append("**禁止导入**:")
        for f in forbidden:
            parts.append(f"- `{f}`")
    return "\n".join(parts) if parts else "（rules.yaml 未配置 imports）"


def _render_naming(rules: Dict[str, Any]) -> str:
    naming = rules.get("naming") or {}
    if not naming:
        return "（rules.yaml 未配置 naming）"
    return "\n".join(f"- **{k}**: {v}" for k, v in naming.items())


def _render_stats(project_context: Dict[str, Any]) -> str:
    summary = project_context.get("summary") or {}
    if not summary:
        return "（尚未运行 scan，或扫描结果缺失）"
    return (
        f"- 文件数: {summary.get('total_files', 0)}\n"
        f"- 组件:   {summary.get('total_components', 0)}\n"
        f"- Hooks:  {summary.get('total_hooks', 0)}\n"
        f"- APIs:   {summary.get('total_apis', 0)}\n"
        f"- 类型:   {summary.get('total_types', 0)}"
    )


def _render_top_items(items: List[Dict[str, Any]], label: str, limit: int = 15) -> str:
    if not items:
        return f"_暂无 {label}_"
    lines = []
    for it in items[:limit]:
        name = it.get("name") or "(unnamed)"
        path = it.get("file_path") or ""
        lines.append(f"- `{name}` — {path}")
    if len(items) > limit:
        lines.append(f"- _… 还有 {len(items) - limit} 个 {label}（详见 project-context.json）_")
    return "\n".join(lines)


def _render_lessons(lessons: List[Dict[str, Any]], limit: int = 20) -> str:
    if not lessons:
        return "_暂无经验记录；可用 `harness lesson add` 添加_"
    parts = []
    for l in lessons[:limit]:
        sev = l.get("severity") or "warning"
        title = l.get("title") or "(untitled)"
        body = (l.get("content") or "").strip()
        # 限制单条 lesson 字数，避免文档膨胀
        if len(body) > 300:
            body = body[:300] + "…"
        applies = ", ".join(l.get("applies_to") or []) or "-"
        parts.append(
            f"### [{sev}] {title}\n\n"
            f"- 适用: `{applies}`\n"
            f"- 关键词: {', '.join(l.get('keywords') or []) or '-'}\n\n"
            f"{body}"
        )
    if len(lessons) > limit:
        parts.append(f"_… 还有 {len(lessons) - limit} 条经验（运行 `harness lesson list`）_")
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# 三个具体 adapter
# ---------------------------------------------------------------------------


class ClaudeAdapter(AgentAdapter):
    """Claude Code 适配器。

    生成自包含的 markdown：用户可在 CLAUDE.md 里 `@.harness/generated/claude.md`
    引入；不依赖运行时 @ 二级跳转，避免 scan 后又要刷 CLAUDE.md 的复杂度。
    """

    @property
    def name(self) -> str:
        return "claude"

    @property
    def display_name(self) -> str:
        return "Claude Code"

    def render_body(self, ctx: GenerateContext) -> str:
        return f"""# 项目规范（Claude Code）

> 由 harness 自动生成。在 `CLAUDE.md` 中通过 `@.harness/generated/claude.md` 引入即可。

## ⛔ 强制规则

### 三层架构

{_render_architecture_table(ctx.rules)}

### 导入规则

{_render_imports(ctx.rules)}

### 命名规范

{_render_naming(ctx.rules)}

## 📊 项目当前状态

{_render_stats(ctx.project_context)}

## 📁 已有组件（节选）

{_render_top_items(ctx.project_context.get("components") or [], "组件")}

## 🪝 已有 Hooks（节选）

{_render_top_items(ctx.project_context.get("hooks") or [], "Hook")}

## 🌐 已有 API（节选）

{_render_top_items(ctx.project_context.get("apis") or [], "API")}

## 🔥 团队经验教训

{_render_lessons(ctx.lessons)}

## 🛠️ 工作流

- 修改代码后 PostToolUse hook 会自动跑 `harness validate`
- 验证失败会以 `decision: block` 返回；按 reason 修改后再保存
- 治理模式可通过 `harness mode <strict|relaxed|off>` 切换
- 自动修复：`harness fix <file> --apply`（仅 import-forbidden 子集）
"""


class ComateAdapter(AgentAdapter):
    """Comate 适配器（无 @ 引用，全部内联）。"""

    @property
    def name(self) -> str:
        return "comate"

    @property
    def display_name(self) -> str:
        return "Comate"

    def render_body(self, ctx: GenerateContext) -> str:
        return f"""# 项目规范（Comate）

> 本项目使用 .harness 框架约束代码规范。本文件由 harness 自动生成。

## ⛔ 强制规则

### 三层架构

{_render_architecture_table(ctx.rules)}

### 导入规则

{_render_imports(ctx.rules)}

### 命名规范

{_render_naming(ctx.rules)}

## 📊 项目当前状态

{_render_stats(ctx.project_context)}

## 📁 可用类型

{_render_top_items(ctx.project_context.get("types") or [], "类型", limit=20)}

## 🌐 可用 API

{_render_top_items(ctx.project_context.get("apis") or [], "API", limit=20)}

## 🔥 团队经验教训

{_render_lessons(ctx.lessons)}
"""


class DuccAdapter(AgentAdapter):
    """Ducc 适配器（项目卡片风格，重列表轻表格）。"""

    @property
    def name(self) -> str:
        return "ducc"

    @property
    def display_name(self) -> str:
        return "Ducc"

    def render_body(self, ctx: GenerateContext) -> str:
        return f"""# 项目规范（Ducc）

> 本项目使用 .harness 框架约束代码规范。本文件由 harness 自动生成。

## ⛔ 强制规则

### 三层架构

{_render_architecture_bullets(ctx.rules)}

### 导入规则

{_render_imports(ctx.rules)}

### 命名规范

{_render_naming(ctx.rules)}

## 📊 项目当前状态

{_render_stats(ctx.project_context)}

## 🧩 已有组件（节选）

{_render_top_items(ctx.project_context.get("components") or [], "组件")}

## 🪝 已有 Hooks（节选）

{_render_top_items(ctx.project_context.get("hooks") or [], "Hook")}

## 🔥 团队经验教训

{_render_lessons(ctx.lessons)}
"""


# ---------------------------------------------------------------------------
# Generator —— 组装数据 + 调度
# ---------------------------------------------------------------------------


@dataclass
class GenerateResult:
    """generate 调用的产物清单。"""

    written: List[str] = field(default_factory=list)   # 写入文件的相对路径


class Generator:
    """统一调度三个 adapter 的渲染与落盘。"""

    DEFAULT_ADAPTERS = (ClaudeAdapter, ComateAdapter, DuccAdapter)

    def __init__(
        self,
        harness_dir: Path,
        version: str = "0.0.0",
        adapters: Optional[List[AgentAdapter]] = None,
    ) -> None:
        self.harness_dir = Path(harness_dir).resolve()
        self.version = version
        self.adapters: List[AgentAdapter] = (
            adapters if adapters is not None else [cls() for cls in self.DEFAULT_ADAPTERS]
        )

    # -- 公共 API -----------------------------------------------------------

    def generate_all(self) -> GenerateResult:
        ctx = self._build_context()
        result = GenerateResult()
        out_dir = self.harness_dir / "generated"
        out_dir.mkdir(parents=True, exist_ok=True)

        for adapter in self.adapters:
            target = adapter.target_path(self.harness_dir)
            content = adapter.render(ctx)
            target.write_text(content, encoding="utf-8")
            # 用相对 .harness/ 的展示路径
            try:
                rel = str(target.relative_to(self.harness_dir.parent))
            except ValueError:
                rel = str(target)
            result.written.append(rel)
        return result

    # -- 内部：数据装载 ------------------------------------------------------

    def _build_context(self) -> GenerateContext:
        rules = self._load_rules()
        project_context = self._load_project_context()
        lessons = self._load_lessons()
        return GenerateContext(
            rules=rules,
            project_context=project_context,
            lessons=lessons,
            version=self.version,
            timestamp=_dt.datetime.now().isoformat(timespec="seconds"),
        )

    def _load_rules(self) -> Dict[str, Any]:
        rules_file = self.harness_dir / "rules.yaml"
        if not rules_file.exists():
            return {}
        try:
            import yaml
            return yaml.safe_load(rules_file.read_text(encoding="utf-8")) or {}
        except Exception:
            return {}

    def _load_project_context(self) -> Dict[str, Any]:
        ctx_file = self.harness_dir / "context" / "project-context.json"
        if not ctx_file.exists():
            return {}
        try:
            return json.loads(ctx_file.read_text(encoding="utf-8")) or {}
        except (json.JSONDecodeError, OSError):
            return {}

    def _load_lessons(self) -> List[Dict[str, Any]]:
        """从 ExperienceMarket 拉所有未过期 lesson，按 created_at 倒序。"""
        # 延迟 import：避免 adapter 单测必须依赖经验市场
        from lib.experience_market import ExperienceMarket
        from dataclasses import asdict

        market = ExperienceMarket(harness_dir=self.harness_dir)
        all_lessons = market.list_lessons()

        now = _dt.datetime.now()
        active = []
        for l in all_lessons:
            if l.expires_at:
                try:
                    if _dt.datetime.fromisoformat(l.expires_at) < now:
                        continue
                except ValueError:
                    pass  # 解析失败 → 当作未过期保留
            active.append(asdict(l))

        active.sort(key=lambda d: d.get("created_at") or "", reverse=True)
        return active
