#!/usr/bin/env python3
"""Harness 2.0 Agent 适配器（P1 #9）—— lib/adapter.py

P1 范围（与执行清单一致）：
- 三个适配器：ClaudeAdapter / ComateAdapter / DuccAdapter
- 输出到 .harness/generated/{claude,comate,ducc}.md（不动项目根）
- 文件首行带时间戳 + 版本注释；用户改这些文件不会被尊重，下次 scan 会盖掉
- 内容来源：rules.yaml + context/project-context.json + memory/lessons/
- 经验注入：把 ExperienceMarket.list_lessons() 中未过期的 lesson 摘要整合进文档
  （静态注入：scan 时一次性渲染到 generated/*.md，由 CLAUDE.md 的 @-import 注入会话上下文）

设计原则：
- 每个 adapter 的 render() 是纯函数：输入 GenerateContext，输出 markdown 字符串
- Generator 只负责组装数据 + 调度落盘；adapter 不直接读盘
- scan 缺失（首次启动）时 generate 仍能跑，只是缺统计部分
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# 数据载体
# ---------------------------------------------------------------------------


@dataclass
class GenerateContext:
    """生成所需的全部数据。"""

    rules: Dict[str, Any]
    project_context: Dict[str, Any]      # project-context.json；缺失时为 {}
    lessons: List[Dict[str, Any]]         # Lesson 序列化后的 dict，已过滤过期
    version: str
    timestamp: str                        # ISO 8601
    # README adapter 专用：用于头部注释里写「源文件指纹」，让 drift check 不
    # 需要重跑 generate 就能比对是否过期。其它 adapter 不消费这两个字段。
    mode: str = "strict"                  # 当前治理模式（来自 mode-config.json）
    source_hashes: Dict[str, str] = field(default_factory=dict)  # 文件名 → sha8
    # A1 接通点:experience_market.max_lessons 控制 brief 注入条数上限
    max_lessons: int = 10


# ---------------------------------------------------------------------------
# Adapter 基类
# ---------------------------------------------------------------------------


class AgentAdapter(ABC):
    """单个 Agent 的渲染规则。"""

    @property
    @abstractmethod
    def name(self) -> str:
        """文件名（不含扩展名），如 'claude'。"""

    @property
    def display_name(self) -> str:
        """人读名称，用于注释里显示。"""
        return self.name

    @abstractmethod
    def render_body(self, ctx: GenerateContext) -> str:
        """渲染除头部注释外的正文。"""

    # -- 通用入口 -----------------------------------------------------------

    def render(self, ctx: GenerateContext) -> str:
        header = (
            f"<!-- generated by harness {ctx.version} at {ctx.timestamp}"
            f" for {self.display_name}; do not edit, run `harness generate` to refresh -->\n\n"
        )
        return header + self.render_body(ctx).rstrip() + "\n"

    def target_path(self, harness_dir: Path) -> Path:
        return harness_dir / "generated" / f"{self.name}.md"

    # -- 写盘（README adapter 会 override 以保留手写区） ---------------------

    def write_to(self, harness_dir: Path, ctx: GenerateContext) -> Path:
        target = self.target_path(harness_dir)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.render(ctx), encoding="utf-8")
        return target


# ---------------------------------------------------------------------------
# 通用渲染片段（三个 adapter 共享）
# ---------------------------------------------------------------------------


def _render_architecture_table(rules: Dict[str, Any]) -> str:
    layers = (rules.get("architecture") or {}).get("layers") or []
    if not layers:
        return "（rules.yaml 未配置 architecture.layers）"
    lines = ["| 层级 | 路径 | 可导入 |", "|------|------|--------|"]
    for layer in layers:
        name = layer.get("name", "")
        paths = ", ".join(layer.get("paths") or []) or "-"
        can = ", ".join(layer.get("can_import") or []) or "（无）"
        lines.append(f"| {name} | {paths} | {can} |")
    return "\n".join(lines)


def _render_architecture_bullets(rules: Dict[str, Any]) -> str:
    layers = (rules.get("architecture") or {}).get("layers") or []
    if not layers:
        return "- （rules.yaml 未配置 architecture.layers）"
    lines = []
    for layer in layers:
        name = layer.get("name", "")
        paths = ", ".join(layer.get("paths") or []) or "-"
        can = ", ".join(layer.get("can_import") or []) or "无"
        lines.append(f"- **{name}** (`{paths}`) → 可导入: {can}")
    return "\n".join(lines)


def _render_sub_layer_convention(rules: Dict[str, Any]) -> str:
    """渲染 architecture.sub_layer_convention 表格。

    有配置时返回完整的 markdown 小节；无配置时返回空字符串（调用方不渲染整节）。

    规则摘要也写进文档，避免 Agent 误以为只有 paths 前缀匹配，转而错误降低
    治理模式来绕过拦截。
    """
    convention = ((rules.get("architecture") or {}).get("sub_layer_convention") or {})
    if not isinstance(convention, dict) or not convention:
        return ""
    lines = [
        "### 局部子目录归层（sub_layer_convention）",
        "",
        "> **优先级高于 paths 前缀匹配。**"
        " 文件归层时先在路径各部分里查下表目录名（从深到浅），命中即用；"
        "未命中才走 `architecture.layers[].paths` 前缀。",
        "> 示例：`src/frontend/module/**/components/*.tsx` 命中 `components` → 归为"
        " `component` 层，**不**受 `src/frontend/module/` 前缀影响。",
        "",
        "| 目录名 | 归属层 |",
        "|--------|--------|",
    ]
    for dir_name, layer_name in convention.items():
        lines.append(f"| `{dir_name}` | {layer_name} |")
    return "\n".join(lines)


def _render_imports(rules: Dict[str, Any]) -> str:
    imp = rules.get("imports") or {}
    allowed = imp.get("allowed_prefixes") or []
    forbidden = imp.get("forbidden_imports") or []
    parts = []
    if allowed:
        parts.append("**允许前缀**: " + ", ".join(f"`{p}`" for p in allowed))
    if forbidden:
        parts.append("**禁止导入**:")
        for f in forbidden:
            parts.append(f"- `{f}`")
    return "\n".join(parts) if parts else "（rules.yaml 未配置 imports）"


def _render_naming(rules: Dict[str, Any]) -> str:
    naming = rules.get("naming") or {}
    if not naming:
        return "（rules.yaml 未配置 naming）"
    return "\n".join(f"- **{k}**: {v}" for k, v in naming.items())


def _render_project_constraints(rules: Dict[str, Any]) -> str:
    """B8: 渲染 `project_constraints` —— 项目级硬约束(必读)。

    rules.yaml schema::

        project_constraints:
          - title: "不允许 default export"
            why: "Tree-shake 友好;rename refactor 安全。"
            example: "export const Foo = ...; ❌ export default Foo;"
          - "纯字符串也行,直接当一条约束"

    返回值为空字符串 → adapter 不渲染整个章节。
    缺 title 的 dict 项会被静默跳过(generate 时不应该把"(未命名约束)"这种
    bug 视觉糊到 generated/*.md 里;人写漏 title 的概率远大于故意留空)。
    """
    items = (rules or {}).get("project_constraints") or []
    if not isinstance(items, list) or not items:
        return ""
    lines = []
    idx = 0
    for item in items:
        if isinstance(item, str):
            stripped = item.strip()
            if not stripped:
                continue
            idx += 1
            lines.append(f"{idx}. {stripped}")
        elif isinstance(item, dict):
            title = (item.get("title") or "").strip()
            if not title:
                # 缺 title 的 dict 项跳过 —— 见 docstring
                continue
            idx += 1
            lines.append(f"{idx}. **{title}**")
            why = item.get("why")
            if why:
                lines.append(f"   - 为什么: {why}")
            example = item.get("example")
            if example:
                lines.append(f"   - 示例: `{example}`")
    return "\n".join(lines)


def _render_constraints_section(rules: Dict[str, Any]) -> str:
    """渲染 ## 🚨 项目硬约束 章节;无约束时返回空字符串(整段不出现)。

    注:返回值不带尾部空行 —— 由 `_render_shared_body` 的 `"\\n\\n".join` 统一处理
    section 间空行,避免双空行拼接。
    """
    body = _render_project_constraints(rules)
    if not body:
        return ""
    return (
        "## 🚨 项目硬约束(必读)\n\n"
        "> 业务级硬约束,优先于下方架构/导入/命名规范。违反这些约束的代码"
        "应直接拒绝;不写在 lessons 里因为 lesson 是经验、约束是底线。\n\n"
        f"{body}"
    )


def _render_stats(project_context: Dict[str, Any]) -> str:
    summary = project_context.get("summary") or {}
    if not summary:
        return "（尚未运行 scan，或扫描结果缺失）"
    return (
        f"- 文件数: {summary.get('total_files', 0)}\n"
        f"- 组件:   {summary.get('total_components', 0)}\n"
        f"- Hooks:  {summary.get('total_hooks', 0)}\n"
        f"- APIs:   {summary.get('total_apis', 0)}\n"
        f"- 类型:   {summary.get('total_types', 0)}"
    )


def _render_top_items(items: List[Dict[str, Any]], label: str, limit: int = 15) -> str:
    if not items:
        return f"_暂无 {label}_"
    lines = []
    for it in items[:limit]:
        name = it.get("name") or "(unnamed)"
        path = it.get("file_path") or ""
        lines.append(f"- `{name}` — {path}")
    if len(items) > limit:
        lines.append(f"- _… 还有 {len(items) - limit} 个 {label}（详见 project-context.json）_")
    return "\n".join(lines)


def _render_lessons(lessons: List[Dict[str, Any]], limit: int = 20) -> str:
    if not lessons:
        return "_暂无经验记录；可用 `harness lesson add` 添加_"
    parts = []
    for l in lessons[:limit]:
        sev = l.get("severity") or "warning"
        title = l.get("title") or "(untitled)"
        body = (l.get("content") or "").strip()
        # 限制单条 lesson 字数，避免文档膨胀
        if len(body) > 300:
            body = body[:300] + "…"
        applies = ", ".join(l.get("applies_to") or []) or "-"
        parts.append(
            f"### [{sev}] {title}\n\n"
            f"- 适用: `{applies}`\n"
            f"- 关键词: {', '.join(l.get('keywords') or []) or '-'}\n\n"
            f"{body}"
        )
    if len(lessons) > limit:
        parts.append(f"_… 还有 {len(lessons) - limit} 条经验（运行 `harness lesson list`）_")
    return "\n\n".join(parts)


def _render_lessons_brief(lessons: List[Dict[str, Any]], limit: int = 30) -> str:
    """精简版：只输出 title + applies_to + 关键词 + 一行摘要。

    给 Claude / Comate / Ducc 的 generated/*.md 用 —— 系统提示词只承担「索引」职责，
    正文由 PostToolUse hook 的 inject-lessons.sh 按当前文件路径动态注入。
    """
    if not lessons:
        return ("_暂无经验记录；可用 `harness lesson add` 添加。"
                "写代码时若有相关经验会通过 PostToolUse 自动注入。_")

    header = (
        "> 以下仅列标题与适用范围；写代码时相关经验会通过 PostToolUse hook "
        "自动注入完整正文。如需现在查看：`harness lesson show <id>`。\n"
    )
    parts = [header]
    for l in lessons[:limit]:
        sev = l.get("severity") or "warning"
        title = l.get("title") or "(untitled)"
        applies = ", ".join(l.get("applies_to") or []) or "-"
        keywords = ", ".join(l.get("keywords") or []) or "-"
        # 一行摘要：取正文首行（截断到 80 字）
        body = (l.get("content") or "").strip().splitlines()
        first_line = body[0].strip() if body else ""
        if len(first_line) > 80:
            first_line = first_line[:80] + "…"
        lid = l.get("id") or "?"
        line = f"- **[{sev}]** {title} `[{lid}]` — 适用 `{applies}`；关键词 {keywords}"
        if first_line:
            line += f"\n  > {first_line}"
        parts.append(line)
    if len(lessons) > limit:
        parts.append(f"_… 还有 {len(lessons) - limit} 条经验（运行 `harness lesson list`）_")
    return "\n".join(parts)


def _render_new_command_help(rules: Dict[str, Any]) -> str:
    """渲染 `harness new` 用法 —— 给 Agent / 人读版共用。

    动态从 rules 取出已注册的 kinds，避免 README 写死后和 rules 不同步；
    例子里的 default_dir 也按 rules 当前值来，让 `--path` 用法对得上现实。
    """
    kinds_cfg = ((rules or {}).get("templates") or {}).get("kinds") or {}
    if not isinstance(kinds_cfg, dict) or not kinds_cfg:
        # 兜底：rules.yaml 未注册任何 kind 时给固定文案（layer.paths 推断目录）
        kinds_str = "component / page / hook / service / type"
        examples = (
            "- `harness new component UserAvatar`"
            " → `src/components/UserAvatar.tsx`（按 layer.paths 推断）\n"
            "- `harness new component UserAvatar --path src/widgets/`"
            " → `src/widgets/UserAvatar.tsx`（覆盖默认目录）\n"
            "- `harness new hook useTodos --force`"
            " → 同名已存在时也强制建（默认拒绝防覆盖）"
        )
        return _NEW_HELP_TEMPLATE.format(kinds=kinds_str, examples=examples)

    kinds_list = list(kinds_cfg.keys())
    kinds_str = " / ".join(kinds_list)
    # 挑 component（如果有）作为示例 kind，否则用第一个
    sample_kind = "component" if "component" in kinds_cfg else kinds_list[0]
    sample_dir = (kinds_cfg.get(sample_kind) or {}).get("default_dir") or "src/"
    sample_dir = sample_dir.rstrip("/") + "/"
    sample_ext = (kinds_cfg.get(sample_kind) or {}).get("extension") or ".tsx"
    examples = (
        f"- `harness new {sample_kind} UserAvatar`"
        f" → `{sample_dir}UserAvatar{sample_ext}`\n"
        f"- `harness new {sample_kind} UserAvatar --path src/widgets/`"
        f" → `src/widgets/UserAvatar{sample_ext}`（覆盖默认目录）\n"
        f"- `harness new {sample_kind} UserAvatar --force`"
        f" → 同名已存在时也强制建（默认拒绝防覆盖）"
    )
    return _NEW_HELP_TEMPLATE.format(kinds=kinds_str, examples=examples)


_NEW_HELP_TEMPLATE = """```
harness new <kind> <name> [--path <dir>] [--force]
```

- `<kind>`：{kinds}
- `<name>`：文件名（去扩展名），如 `UserAvatar`
- `--path <dir>`：自定义落盘目录，覆盖 `rules.yaml` 默认路径
- `--force`：目标文件已存在或同名冲突时强制创建

**示例**：

{examples}

> 优先级：`--path` > `rules.yaml templates.kinds.<kind>.default_dir` > 算法兜底"""


# ---------------------------------------------------------------------------
# B4: 三个 Agent adapter 共享的 body 拼装
# ---------------------------------------------------------------------------


def _render_shared_body(
    ctx: GenerateContext,
    *,
    architecture_style: str = "table",
    sections: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """三个 Agent adapter 共用的正文渲染。

    architecture_style: 'table' (Claude/Comate) | 'bullets' (Ducc)
    sections: 「项目状态」之后的若干自定义 section,每条 dict 形如
              ``{"title": "## 📁 已有组件", "key": "components", "label": "组件",
                "limit": 15}`` —— Claude/Ducc 列组件+hooks,Comate 列 types+apis。

    其它共享部分(标题段、强制规则、命名、新建文件帮助、经验索引)在这里统一渲染。
    """
    arch_block = (
        _render_architecture_bullets(ctx.rules)
        if architecture_style == "bullets"
        else _render_architecture_table(ctx.rules)
    )
    sub_layer_block = _render_sub_layer_convention(ctx.rules)

    constraints = _render_constraints_section(ctx.rules)

    parts: List[str] = []
    if constraints:
        parts.append(constraints)
    arch_section = ["## ⛔ 强制规则", "### 三层架构", arch_block]
    if sub_layer_block:
        arch_section.append(sub_layer_block)
    parts.extend(arch_section)
    parts.extend([
        "### 导入规则",
        _render_imports(ctx.rules),
        "### 命名规范",
        _render_naming(ctx.rules),
        "## 📊 项目当前状态",
        _render_stats(ctx.project_context),
    ])

    for sec in sections or []:
        parts.append(sec["title"])
        parts.append(_render_top_items(
            ctx.project_context.get(sec["key"]) or [],
            sec.get("label", sec["key"]),
            limit=sec.get("limit", 15),
        ))

    parts.append("## 🔥 团队经验教训（索引）")
    parts.append(_render_lessons_brief(ctx.lessons, limit=ctx.max_lessons))
    parts.append("## 🆕 新建文件（harness new）")
    parts.append(_render_new_command_help(ctx.rules))

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# 三个具体 adapter
# ---------------------------------------------------------------------------


class ClaudeAdapter(AgentAdapter):
    """Claude Code 适配器。

    生成自包含的 markdown：用户可在 CLAUDE.md 里 `@.harness/generated/claude.md`
    引入；不依赖运行时 @ 二级跳转，避免 scan 后又要刷 CLAUDE.md 的复杂度。
    """

    @property
    def name(self) -> str:
        return "claude"

    @property
    def display_name(self) -> str:
        return "Claude Code"

    def render_body(self, ctx: GenerateContext) -> str:
        header = (
            "# 项目规范（Claude Code）\n\n"
            "> 由 harness 自动生成。在 `CLAUDE.md` 中通过 "
            "`@.harness/generated/claude.md` 引入即可。\n\n"
        )
        body = _render_shared_body(
            ctx,
            architecture_style="table",
            sections=[
                {"title": "## 📁 已有组件（节选）", "key": "components", "label": "组件"},
                {"title": "## 🪝 已有 Hooks（节选）", "key": "hooks", "label": "Hook"},
                {"title": "## 🌐 已有 API（节选）", "key": "apis", "label": "API"},
            ],
        )
        # Claude 风格特化:在「经验索引」之前插入工作流说明
        # 简单做法:直接在 body 末尾追加;_render_shared_body 已含 经验+新建文件,
        # 这里再补 Claude 独有的工作流段(放在最后,跟当前结构一致)
        workflow = (
            "\n\n## 🛠️ 工作流\n\n"
            "- 修改代码后 PostToolUse hook 会自动跑 `harness validate`\n"
            "- 同一 PostToolUse 还会按当前 file_path + 内容动态注入相关经验"
            "（inject-lessons.sh）\n"
            "- 验证失败会以 `decision: block` 返回；按 reason 修改后再保存\n"
            "- 不要为了绕过验证自行执行 `harness mode relaxed/off`；"
            "只有用户明确要求调整治理策略时才切换模式\n"
            "- 治理模式可通过 `harness mode <strict|relaxed|off>` 切换\n"
            "- 自动修复：`harness fix <file> --apply`（仅 import-forbidden 子集）\n\n"
            "## 🧭 rules.yaml 起草流程\n\n"
            "- 新项目接入时，优先运行 `harness probe --json` 获取项目 facts\n"
            "- Agent 根据 facts、项目上下文和用户确认，起草 `rules.yaml`\n"
            "- 使用 `harness init --rules <file>` 写入 `.harness/rules.yaml`\n"
            "- 写入后运行 `harness scan` 刷新 `.harness/generated/claude.md`\n"
            "- 不确定的层归属必须询问用户，不要仅凭目录名自行决策"
        )
        return header + body + workflow + "\n"


class ComateAdapter(AgentAdapter):
    """Comate 适配器（无 @ 引用，全部内联）。"""

    @property
    def name(self) -> str:
        return "comate"

    @property
    def display_name(self) -> str:
        return "Comate"

    def render_body(self, ctx: GenerateContext) -> str:
        header = (
            "# 项目规范（Comate）\n\n"
            "> 本项目使用 .harness 框架约束代码规范。本文件由 harness 自动生成。\n\n"
        )
        body = _render_shared_body(
            ctx,
            architecture_style="table",
            sections=[
                {"title": "## 📁 可用类型", "key": "types",
                 "label": "类型", "limit": 20},
                {"title": "## 🌐 可用 API", "key": "apis",
                 "label": "API", "limit": 20},
            ],
        )
        return header + body + "\n"


class DuccAdapter(AgentAdapter):
    """Ducc 适配器（项目卡片风格，重列表轻表格）。"""

    @property
    def name(self) -> str:
        return "ducc"

    @property
    def display_name(self) -> str:
        return "Ducc"

    def render_body(self, ctx: GenerateContext) -> str:
        header = (
            "# 项目规范（Ducc）\n\n"
            "> 本项目使用 .harness 框架约束代码规范。本文件由 harness 自动生成。\n\n"
        )
        body = _render_shared_body(
            ctx,
            architecture_style="bullets",
            sections=[
                {"title": "## 🧩 已有组件（节选）", "key": "components", "label": "组件"},
                {"title": "## 🪝 已有 Hooks（节选）", "key": "hooks", "label": "Hook"},
            ],
        )
        return header + body + "\n"


# ---------------------------------------------------------------------------
# README adapter：人读版规则说明书（自动区 + 手写区）
# ---------------------------------------------------------------------------


# 手写区标记：drift check 只校验 AUTOGENERATED 区块的哈希，标记之外的内容
# 由人维护、generate 不会动。改这两个常量等于让历史 README.md 全部变成"无手
# 写区"，请勿修改。
README_HANDWRITTEN_BEGIN = "<!-- HANDWRITTEN START — content below is preserved by harness generate -->"
README_HANDWRITTEN_END = "<!-- HANDWRITTEN END -->"

# 自动区开始/结束：auto-gen 内容包在这两个标记之间，drift check 比对的就是
# 这之间的内容哈希。其它 adapter 整个文件都是自动区，不需要这套 marker。
README_AUTO_BEGIN = "<!-- AUTOGENERATED START — do not edit; run `harness generate` to refresh -->"
README_AUTO_END = "<!-- AUTOGENERATED END -->"

# 默认手写区模板（首次创建 README 时写入）
DEFAULT_HANDWRITTEN_BODY = """## 背景与原则（手写区）

> 本节由人维护，`harness generate` 不会覆盖。写写为什么这么定规矩、关键决
> 策的取舍、新人 onboarding 时容易踩的坑。

- _示例_：在 `rules.yaml` 的 `imports.forbidden_imports` 列出团队历史踩坑
  的路径前缀（例如已废弃的 `@/legacy` / 直接耦合 mock 的 `@/api/mockApi`
  之类），并在 `imports.rewrites` 给出可机械替换的目标，让 `harness fix`
  能在本地把它们一键纠正回来。

## FAQ

- _Q: 想加一条新规则？_ → 改 `.harness/rules.yaml`，跑 `harness generate`，
  PR 里这份 README 的 diff 会自动反映出来。
- _Q: 想加一条团队经验？_ → `harness lesson add --title ... --content ...`，
  会自动 generate。
- _Q: 想临时关掉验证？_ → `harness mode off`（会改 `mode-config.json`，
  请记得提交或在 PR 里说明）。
"""


# README 头部接入说明（位于标题之后、AUTOGENERATED 块之前）。
# 这块是固定文案,但**不**进 AUTOGENERATED marker —— 因为它和 rules/lessons
# 无关,不会随 generate 漂移。drift check 只校验 marker 之间的内容,这里改了
# 不会触发 README drift。
_ONBOARDING_BLOCK = """## 🚀 在新项目中接入 harness

> 把 `.harness/` 整个目录拷到目标项目根，**一条命令搞定**。

```bash
# 一键接入：内部按序跑 init --yes + install + scan
.harness/commands/harness setup --agent claude       # 或 ducc / baidu-cc
```

`setup` 等价于下面三步，但**对所有 conflict 走默认值，无交互**：

```bash
.harness/commands/harness init --yes
.harness/commands/harness install --agent claude
.harness/commands/harness scan
```

### 想看探测细节 / 手动选 conflict？

用 `--interactive` 让 init 阶段弹问题让你选；或者拆成原始三步逐个跑：

```bash
.harness/commands/harness setup --agent claude --interactive   # init 走交互
# 或
.harness/commands/harness init               # 完全交互
.harness/commands/harness init --dry-run     # 只看 plan 不写盘
.harness/commands/harness init --json        # CI / 程序消费用
```

### 老项目接入（务实派）

老项目的存量违规通常**不敢碰**——动一行可能炸一片。建议**只管增量，不管存量**：

```bash
# 1) 一键接入
.harness/commands/harness setup --agent claude

# 2) 直接 strict（不要"先 relaxed 后收紧"——老代码一辈子都不会被收紧）
.harness/commands/harness mode strict

# 3) 不跑 harness check，不修存量违规
#    只让"今天起 Agent 改的代码"符合规则
#    历史代码什么样什么样
```

之后只有当 Agent 主动去改某个老文件时，PostToolUse hook 才会拦它——届时 Agent 会顺手把那一处违规修了，**渐进式**清理而不是一次性大改。

如果存量违规你**确实想看一眼**（不打算修，只是评估）：

```bash
.harness/commands/harness check --json | python3 -m json.tool | head -40
```

### init 三段式做了什么

`setup` 内部跑的 `init` 是三段式（probe → resolve → apply）：

| 阶段 | 干什么 | 产出 |
|------|--------|------|
| probe   | 只读扫一遍项目根：tsconfig.json / package.json / src/ / .eslintrc / .gitignore | `ProbeReport` |
| resolve | 对照出厂默认 `rules.yaml`，自动采纳能采纳的，分歧抛 `Conflict` 让用户选 | `ProposedPlan` |
| apply   | 把用户答复（或 `--yes` 走 `default_choice`）落到 rules.yaml + 必要目录 | 写盘 |

**自动采纳的**（不打扰用户）：
- tsconfig.json `paths` 别名（采纳探测值，与默认一致时静默沿用）
- layer 路径与默认不同时直接采纳现状（例：默认 `component.paths=[src/pages/, src/components/]`，但项目只有 `src/components/` → 采纳）
- 探测到的框架 / 包管理器（只打 info note，不进 rules）

**抛 conflict 让用户拍板的**（`--yes` / `setup` 默认走 default_choice）：
- `src/` 下未识别的目录（例 `src/utils/`）：映射到某 layer / 加进 `exclude_dirs` / 先放着
- 命名风格背离默认（样本 ≥ 3 且实际命中率 < 50%）：保留默认 / 采纳现状风格 / 不校验该层

**不会自动猜的**：
- `imports.forbidden_imports` / `imports.rewrites` —— 业务语义无法探测，需要手写

接入后建议看 [`.harness/docs/presets.md`](docs/presets.md) 对照常见项目形态调整。

---

"""



class ReadmeAdapter(AgentAdapter):
    """人读版规则说明书 .harness/README.md（GitHub/IDE 进 .harness/ 默认渲染）。

    与 Agent 规则文件的差异：
    - 不放在 `generated/`，直接写到 `.harness/README.md`，进 git
    - 文件分两段：AUTOGENERATED 自动区（每次 generate 重写）+ HANDWRITTEN
      手写区（首次创建落默认模板，之后保留用户编辑）
    - 头部带源文件 sha8 指纹，drift check 不必重跑 generate 就能判断过期
    - 内容是「当前项目规则快照 + 怎么改规则」，不重复 ARCHITECTURE.md 的
      工具内部实现
    """

    @property
    def name(self) -> str:
        return "readme"

    @property
    def display_name(self) -> str:
        return "人读版规则说明书"

    def target_path(self, harness_dir: Path) -> Path:
        # 直接写 .harness/README.md，不进 generated/
        return harness_dir / "README.md"

    def render(self, ctx: GenerateContext) -> str:
        # 由 write_to 控制装配（需要保留手写区），单独 render() 给单测用
        auto_block = self._render_auto_block(ctx)
        handwritten_block = self._wrap_handwritten(DEFAULT_HANDWRITTEN_BODY)
        return self._compose(ctx, auto_block, handwritten_block)

    def render_body(self, ctx: GenerateContext) -> str:
        # ReadmeAdapter override 了 render()，body 只是兼容基类约定
        return self._render_auto_block(ctx)

    def write_to(self, harness_dir: Path, ctx: GenerateContext) -> Path:
        target = self.target_path(harness_dir)
        target.parent.mkdir(parents=True, exist_ok=True)

        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        handwritten_body = self._extract_handwritten(existing)
        if handwritten_body is None:
            handwritten_body = DEFAULT_HANDWRITTEN_BODY

        auto_block = self._render_auto_block(ctx)
        handwritten_block = self._wrap_handwritten(handwritten_body)
        target.write_text(self._compose(ctx, auto_block, handwritten_block), encoding="utf-8")
        return target

    # -- 自动区渲染 ----------------------------------------------------------

    def _compose(self, ctx: GenerateContext, auto_block: str, handwritten_block: str) -> str:
        # 头部：标题 + 接入说明 + 简介 + 源文件指纹注释（机读，drift check 用）
        sources_line = " ".join(
            f"{name}@{sha}" for name, sha in sorted(ctx.source_hashes.items())
        ) or "(none)"
        header = (
            f"# Harness 项目规则说明（人读版）\n\n"
            + _ONBOARDING_BLOCK
            + f"<!-- AUTOGENERATED by harness {ctx.version} at {ctx.timestamp} — DO NOT EDIT THE AUTOGENERATED BLOCK -->\n"
            f"<!-- sources: {sources_line} -->\n\n"
            f"> 这份文档是这个项目当前规则的**快照**，由 `harness generate` 自动产出。\n"
            f"> 想改规则？请改 `.harness/rules.yaml`、`.harness/memory/lessons/`、\n"
            f"> 或 `.harness/mode-config.json`，然后跑 `harness generate` 重生成本文件。\n\n"
        )
        return header + auto_block + "\n\n" + handwritten_block

    def _render_auto_block(self, ctx: GenerateContext) -> str:
        body = self._render_auto_body(ctx)
        # 用 marker 包起来，drift check 比对的就是 marker 之间的内容
        return f"{README_AUTO_BEGIN}\n\n{body}\n\n{README_AUTO_END}"

    def _render_auto_body(self, ctx: GenerateContext) -> str:
        sub_layer_section = _render_sub_layer_convention(ctx.rules)
        sub_layer_block = f"\n\n{sub_layer_section}" if sub_layer_section else ""
        return f"""{_render_constraints_section(ctx.rules)}## ⛔ 当前强制规则

### 三层架构

{_render_architecture_table(ctx.rules)}{sub_layer_block}

> 配置位置：`.harness/rules.yaml` → `architecture.layers`

### 导入规则

{_render_imports(ctx.rules)}

> 配置位置：`.harness/rules.yaml` → `imports`

### 命名规范

{_render_naming(ctx.rules)}

> 配置位置：`.harness/rules.yaml` → `naming`

## 🎚️ 当前治理模式

- **mode**: `{ctx.mode}`
- 切换：`harness mode <strict|relaxed|off>`
  - `strict`：所有 error/warning/info 全拦截
  - `relaxed`：仅 error 拦截
  - `off`：完全关闭（PostToolUse hook 直接放行）
- 配置位置：`.harness/mode-config.json`

## 📊 项目当前状态（来自最近一次 scan）

{_render_stats(ctx.project_context)}

## 🔥 团队经验教训（节选）

{_render_lessons(ctx.lessons, limit=10)}

> 增删经验：`harness lesson add` / `harness lesson remove <id>`
> 经验存放在：`.harness/memory/lessons/`

## 🛠️ 工作流速查

- 修改 `src/**/*.{{ts,tsx,d.ts}}` → PostToolUse hook 自动跑 `harness validate`
- 拦截了？看错误信息按 reason 改完再保存即可
- 新建文件用 `harness new <kind> <name> [--path <dir>]`（详见 [`generated/claude.md`](generated/claude.md) 末节）
- 自动修复 `import-forbidden` 子集：`harness fix <file> --apply`
- 同步团队经验：`harness sync`
- 体检环境：`harness doctor`

## ✏️ 怎么改规则

| 想做什么 | 改哪里 | 之后跑什么 |
|---------|--------|-----------|
| 加/改架构层、导入白黑名单、命名规范 | `.harness/rules.yaml` | `harness generate` |
| 加一条团队经验 | `harness lesson add ...` | （CLI 已自动 generate） |
| 改治理模式 | `harness mode strict\\|relaxed\\|off` | （CLI 已自动落盘） |
| 改 hook 触发条件 | `.claude/settings.json` | 重启 Agent 会话 |

> 修改 `rules.yaml` / `lessons/` / `mode-config.json` 后，本文件需要重生成；
> 否则 `harness doctor` 会报 README drift。"""

    # -- 手写区抽取 / 包装 ---------------------------------------------------

    @staticmethod
    def _wrap_handwritten(body: str) -> str:
        return (
            f"{README_HANDWRITTEN_BEGIN}\n\n"
            f"{body.strip()}\n\n"
            f"{README_HANDWRITTEN_END}"
        )

    @staticmethod
    def _extract_handwritten(existing: str) -> Optional[str]:
        """从已有文件里抠出手写区内容（不含 marker）。

        返回 None：文件不存在 / 没有 marker（视为首次生成，落默认模板）
        返回 str：marker 之间的纯内容（已 strip）
        """
        if not existing or README_HANDWRITTEN_BEGIN not in existing or README_HANDWRITTEN_END not in existing:
            return None
        pattern = re.compile(
            re.escape(README_HANDWRITTEN_BEGIN) + r"(.*?)" + re.escape(README_HANDWRITTEN_END),
            flags=re.DOTALL,
        )
        m = pattern.search(existing)
        if not m:
            return None
        return m.group(1).strip()

    # -- drift check 给 doctor 用 --------------------------------------------

    @staticmethod
    def extract_auto_block(existing: str) -> Optional[str]:
        """抠出自动区内容（用于哈希比对），不含 marker。"""
        if README_AUTO_BEGIN not in existing or README_AUTO_END not in existing:
            return None
        pattern = re.compile(
            re.escape(README_AUTO_BEGIN) + r"(.*?)" + re.escape(README_AUTO_END),
            flags=re.DOTALL,
        )
        m = pattern.search(existing)
        return m.group(1).strip() if m else None

    @staticmethod
    def extract_source_hashes(existing: str) -> Dict[str, str]:
        """从 `<!-- sources: name@sha8 ... -->` 注释里抠出指纹。"""
        m = re.search(r"<!--\s*sources:\s*([^>]+?)\s*-->", existing)
        if not m:
            return {}
        out: Dict[str, str] = {}
        for token in m.group(1).split():
            if "@" in token:
                name, sha = token.split("@", 1)
                out[name.strip()] = sha.strip()
        return out



# ---------------------------------------------------------------------------
# Generator —— 组装数据 + 调度
# ---------------------------------------------------------------------------


@dataclass
class GenerateResult:
    """generate 调用的产物清单。"""

    written: List[str] = field(default_factory=list)   # 写入文件的相对路径


# ---------------------------------------------------------------------------
# HooksConfigAdapter —— 把 rules.yaml scanner.* + mode-config.json 编译成
# bash 变量,让 validate-code.sh / inject-lessons.sh 在调 Python CLI 之前先
# 做扩展名/目录前缀过滤(fast-path),省掉 Python 冷启动开销。
#
# 设计:
# - 写到 `.harness/hooks/.config.sh`,入 git(类似 generated/*.md)
# - 文件头部带 marker,人改不会被 generate 尊重
# - hook 只 source 不解析 yaml,失败兜底 → 继续走原路径(向后兼容)
# ---------------------------------------------------------------------------


def _bash_array(items: List[str]) -> str:
    """把 Python 列表转成 bash 数组字面量,内容做最小转义。"""
    quoted = []
    for it in items:
        # 单引号包,内部单引号转成 '\''
        s = str(it).replace("'", "'\\''")
        quoted.append(f"'{s}'")
    return "( " + " ".join(quoted) + " )" if quoted else "()"


class HooksConfigAdapter(AgentAdapter):
    """生成 `.harness/hooks/.config.sh` —— hook fast-path 用的 bash 变量。

    与三个 markdown adapter 不同:
    - 不进 generated/,直接落 hooks/.config.sh
    - 输出是 bash 而非 markdown
    - 不参与 README source_hashes(它本身就是 rules.yaml 的派生)
    """

    @property
    def name(self) -> str:
        return "hooks-config"

    @property
    def display_name(self) -> str:
        return "Hooks fast-path config"

    def target_path(self, harness_dir: Path) -> Path:
        return harness_dir / "hooks" / ".config.sh"

    def render_body(self, ctx: GenerateContext) -> str:
        scanner = (ctx.rules or {}).get("scanner") or {}
        source_root = scanner.get("source_root") or "src"
        if isinstance(source_root, str) and source_root.rstrip("/") == ".":
            source_root = ""
        include_ext = scanner.get("include_extensions") or [".ts", ".tsx", ".d.ts", ".js", ".jsx"]
        exclude_dirs = scanner.get("exclude_dirs") or []
        # exclude_globs 不再输出:复杂 glob 交给 `harness should-validate` CLI 兜底,
        # bash glob (case 模式) 与 Python fnmatch 语义不完全一致(尤其 `**`),
        # 维护两套引擎容易引 bug,不如 fork 一次 CLI 干净。

        market = (ctx.rules or {}).get("experience_market") or {}
        market_enabled = 1 if market.get("enabled", True) else 0

        return (
            f"# Auto-generated by harness {ctx.version} at {ctx.timestamp}\n"
            f"# DO NOT EDIT — run `harness generate` to refresh.\n"
            f"# Sourced by .harness/hooks/*.sh for fast-path filtering before\n"
            f"# invoking the Python CLI. Run `harness doctor` if generated config looks stale.\n"
            f"\n"
            f"HARNESS_SOURCE_ROOT={_bash_quote(source_root)}\n"
            f"HARNESS_INCLUDE_EXT={_bash_array(list(include_ext))}\n"
            f"HARNESS_EXCLUDE_DIRS={_bash_array(list(exclude_dirs))}\n"
            f"HARNESS_MODE={_bash_quote(ctx.mode)}\n"
            f"HARNESS_EXPERIENCE_ENABLED={market_enabled}\n"
        )

    def render(self, ctx: GenerateContext) -> str:
        # 覆盖基类:bash 文件不带 markdown 注释头,直接用 render_body
        return self.render_body(ctx)


def _bash_quote(value: str) -> str:
    s = str(value).replace("'", "'\\''")
    return f"'{s}'"


class Generator:
    """统一调度 adapter 的渲染与落盘。"""

    DEFAULT_ADAPTERS = (ClaudeAdapter, ComateAdapter, DuccAdapter, ReadmeAdapter, HooksConfigAdapter)

    # 哪些文件参与 README 的 source hash —— 改这里等于改 drift check 的口径
    SOURCE_FILES = ("rules.yaml", "mode-config.json")
    LESSONS_DIR = ("memory", "lessons")

    def __init__(
        self,
        harness_dir: Path,
        version: str = "0.0.0",
        adapters: Optional[List[AgentAdapter]] = None,
    ) -> None:
        self.harness_dir = Path(harness_dir).resolve()
        self.version = version
        self.adapters: List[AgentAdapter] = (
            adapters if adapters is not None else [cls() for cls in self.DEFAULT_ADAPTERS]
        )

    # -- 公共 API -----------------------------------------------------------

    def generate_all(self) -> GenerateResult:
        ctx = self._build_context()
        result = GenerateResult()

        for adapter in self.adapters:
            target = adapter.write_to(self.harness_dir, ctx)
            try:
                rel = str(target.relative_to(self.harness_dir.parent))
            except ValueError:
                rel = str(target)
            result.written.append(rel)
        return result

    # -- 内部：数据装载 ------------------------------------------------------

    def _build_context(self) -> GenerateContext:
        rules = self._load_rules()
        project_context = self._load_project_context()
        lessons = self._load_lessons(rules=rules)
        market_cfg = (rules or {}).get("experience_market") or {}
        max_lessons = market_cfg.get("max_lessons", 10)
        if not isinstance(max_lessons, int) or max_lessons <= 0:
            max_lessons = 10
        return GenerateContext(
            rules=rules,
            project_context=project_context,
            lessons=lessons,
            version=self.version,
            timestamp=_dt.datetime.now().isoformat(timespec="seconds"),
            mode=self._load_mode(),
            source_hashes=self._compute_source_hashes(),
            max_lessons=max_lessons,
        )

    def _load_rules(self) -> Dict[str, Any]:
        rules_file = self.harness_dir / "rules.yaml"
        if not rules_file.exists():
            return {}
        try:
            import yaml
            return yaml.safe_load(rules_file.read_text(encoding="utf-8")) or {}
        except Exception:
            return {}

    def _load_project_context(self) -> Dict[str, Any]:
        ctx_file = self.harness_dir / "context" / "project-context.json"
        if not ctx_file.exists():
            return {}
        try:
            return json.loads(ctx_file.read_text(encoding="utf-8")) or {}
        except (json.JSONDecodeError, OSError):
            return {}

    def _load_mode(self) -> str:
        """从 mode-config.json 读当前模式；缺失/损坏返回默认 strict。"""
        mode_file = self.harness_dir / "mode-config.json"
        if not mode_file.exists():
            return "strict"
        try:
            data = json.loads(mode_file.read_text(encoding="utf-8")) or {}
            mode = data.get("mode")
            return mode if isinstance(mode, str) and mode else "strict"
        except (json.JSONDecodeError, OSError):
            return "strict"

    def _compute_source_hashes(self) -> Dict[str, str]:
        """计算 README 关心的源文件指纹。

        - rules.yaml / mode-config.json：单文件取 sha256 前 8 位，缺失记 'missing'
        - lessons：把 lessons/ 下所有 *.md 的内容串起来取一次 sha8（顺序固定，
          与文件名排序一致），目录不存在记 'missing'
        """
        out: Dict[str, str] = {}
        for fname in self.SOURCE_FILES:
            f = self.harness_dir / fname
            out[fname] = _sha8_of_file(f) if f.exists() else "missing"

        lessons_dir = self.harness_dir.joinpath(*self.LESSONS_DIR)
        out["lessons"] = _sha8_of_dir(lessons_dir, suffix=".md") if lessons_dir.exists() else "missing"
        return out

    def _load_lessons(self, rules: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]:
        """从 ExperienceMarket 拉所有未过期 lesson，按 created_at 倒序。

        rules 提供时 experience_market.enabled=false 直接返回空列表(A1 接通点)。
        """
        market_cfg = ((rules or {}).get("experience_market") or {})
        if market_cfg.get("enabled", True) is False:
            return []
        # 延迟 import：避免 adapter 单测必须依赖经验市场
        from lib.experience_market import ExperienceMarket
        from dataclasses import asdict

        market = ExperienceMarket(harness_dir=self.harness_dir)
        all_lessons = market.list_lessons()

        now = _dt.datetime.now()
        active = []
        for l in all_lessons:
            if l.expires_at:
                try:
                    if _dt.datetime.fromisoformat(l.expires_at) < now:
                        continue
                except ValueError:
                    pass  # 解析失败 → 当作未过期保留
            active.append(asdict(l))

        active.sort(key=lambda d: d.get("created_at") or "", reverse=True)
        return active


# ---------------------------------------------------------------------------
# 工具
# ---------------------------------------------------------------------------


def _sha8_of_file(path: Path) -> str:
    """单文件 sha256 前 8 位；读不出来返回 'unreadable'。"""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:8]
    except OSError:
        return "unreadable"


def _sha8_of_dir(path: Path, suffix: str = "") -> str:
    """目录下匹配后缀的所有文件按文件名排序后串起来取 sha8。

    空目录 → 'empty'；读不出来 → 'unreadable'。
    """
    try:
        files = sorted(p for p in path.iterdir() if p.is_file() and p.name.endswith(suffix))
    except OSError:
        return "unreadable"
    if not files:
        return "empty"
    h = hashlib.sha256()
    for f in files:
        h.update(f.name.encode("utf-8"))
        h.update(b"\0")
        try:
            h.update(f.read_bytes())
        except OSError:
            h.update(b"<unreadable>")
        h.update(b"\0")
    return h.hexdigest()[:8]
